# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '10.0' # iOS 최소 버전을 적절히 설정하세요
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MyReactNativeApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # react-native-audio 추가
  pod 'react-native-audio', :path => '../node_modules/react-native-audio'
  # react-native-async-storage 추가
  pod 'RNAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  # 명시적 종속성 추가
  pod 'React-jsi', :path => "#{config[:reactNativePath]}/ReactCommon/jsi"
  pod 'React-jsinspector', :path => "#{config[:reactNativePath]}/ReactCommon/jsinspector"

  target 'MyReactNativeAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Flipper 설정 추가
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['OTHER_CFLAGS'] = '$(inherited) -DFLIPPER_ENABLED=1'
      end
    end
  end
end
